### ISSUE TITLE
 TypeError: getUrlFromSvgString is not a function

### ISSUE THREAD

**Issue by danielnjoo** [zillding/svg-to-url#1]
Running : 

```
var stringToUrl = require('svg-to-url');
const svgoConfig = {/* custom svgo config */};
const getUrlFromSvgString = stringToUrl(svgoConfig);
const resultUrl = getUrlFromSvgString(svg);
```

results in  `TypeError: getUrlFromSvgString is not a function` in Node, any idea what I'm doing wrong? Do I need to pass a real custom svgo config?

**Comment by zillding** [comment]
Sorry for the late reply. I haven't worked no this project for some time until recently. 😢 

To answer your question, the default export takes a file path only.

```
const svgToUrl = require('svg-to-url');
svgToUrl('path/to/file.svg')...
```

If you want to use another exposed api which is to convert a svg string to data url, you need to do
`const { stringToUrl } = require('svg-to-url');`
instead of 
`const stringToUrl = require('svg-to-url');`

Hope it helps. For now, I will close this issue.
